# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: Documentation
description: Report documentation problems or suggest additions.
labels: ["documentation"]
assignees:
  - benelan
body:
  - type: markdown
    attributes:
      value: |
        Thanks for logging an issue, I appreciate the feedback! Please confirm the following before continuing:
        - You are using the latest version, since the issue may already be fixed.
        - There are no [existing issues](/../../issues?q=is%3Aopen+is%3Aissue+label%3Adocumentation) with the documentation request/problem.
            - If there is a duplicate issue, please add a 👍 reaction instead of creating a new one.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be added or fixed?
    validations:
      required: true
  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: Any other helpful information, including examples or suggestions.
    validations:
      required: false
