name: Documentation
description: Report issues with or make requests for documentation
labels: ["docs"]
assignees:
  - benelan
body:
  - type: markdown
    attributes:
      value: |
        Thanks for logging an issue, I appreciate the feedback! Please confirm the following before continuing:
        - You are using the latest version, since the issue may already be fixed.
        - There are no [existing issues](https://github.com/benelan/gh-fzf/issues) with the same report/request.
            - If there is a duplicate issue, please add a 👍 reaction instead of creating a new one.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be added or fixed?
    validations:
      required: true
  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: Any other helpful information, including examples or suggestions.
    validations:
      required: false
